### ISSUE TITLE
FS 4.4 - ViewDocument action um fsbroker-Schema erweitern

### ISSUE THREAD

**Issue by FSDKO** [FrameworkSystemsGmbH/HtmlClient#12]
Für den ASP.net DevExpress-Report-Designer wurde im Java-Client die ViewDocument-Action um das `fsbroker://` Schema erweitert. 
Dies muss im HtmlClient nachgezogen werden.

Siehe auch https://github.com/FrameworkSystemsGmbH/fs/commit/fcc6594d4d44cf6052b954d9a527a05b8b33123d

**Comment by FSDRE** [comment]
Zur Info: `fsbroker://` ist aber auch das Schema, welches im Android-System für die Deep-Links registriert wird. Hat mit ViewDocument nichts zu tun. Das kann aber ggf. Verwirrung stiften:

1. Wenn ich im Android im Browser auf einen fsbroker:// Link klicke, geht der Mobile Client auf und loggt sich am Broker ein
2. Wenn ich fsBroker:// per ViewDocument öffne, öffnet sich das Dokument mit der Broker-Url im Browser

Zwei völlig verschiedene Dinge...

**Comment by FSDKO** [comment]
Dann haben wir jetzt einen Namens-Konflikt - ich glaube aber nicht dass der schlimm ist.
Im ViewDoument() wird das Schema ja umgesetzt - es kommt also niemals zu einem Deep-Link durch. Wir hätten dann nur die Restriktion, dass wir über ViewDocument() keinen Deep-Link verarbeiten können. Außer wir schaffen speziell dafür eine gesonderte Codierung.

Wir haben uns mit dem `fsbroker://` an das Browser-Control angelehnt - da gibt schon seit sehr langer Zeit diese Umsetzung.
Blöd, dass diese Deep-Links jetzt schon länger existieren - ändern kann man jetzt wahrscheinlich nicht mehr.
