### ISSUE TITLE
Beep action support

### ISSUE THREAD

**Issue by FSDKO** [FrameworkSystemsGmbH/HtmlClient#15]
Support for form action `Beep()`.
Maybe also support `BeepDouble()` and `BeepMultiple()`.

This is usefull for scanner applications.

Nice online example:
<https://stackoverflow.com/a/41077092/16082844>
This generates a tone, exact as wee need it for our usecase 😃

**Comment by FSDRE** [comment]
[Commit](https://github.com/FrameworkSystemsGmbH/HtmlClient/commit/357bb5fed9752cb13dceadb1b8c99d6f1e032026)

(Issue vergessen zu referenzieren)
