### ISSUE TITLE
Switch auf Capacitor Barcode Scanner Plugin

### ISSUE THREAD

**Issue by FSDRE** [FrameworkSystemsGmbH/HtmlClient#18]
Bisher wird noch das Phonegapp-Plugin benutzt:

https://www.npmjs.com/package/phonegap-plugin-barcodescanner

Das ist seit der Abkündigung von Phonegapp durch Adobe `deprecated`

Da das Plugin nciht mehr aktualisiert wird, ist es mit Gradle 7.0 (Android Build Tool) nicht mehr kompatibel und kann somit nicht kompiliert werden. Ein Update von Capacitor hebt Gradle aber automatisch von 6.x auf 7.x an. D.h., sollte Capacitor upgedated werden (was nötig ist, um neue Android-Versionen zu unterstützen), dann muss auch das Barcode-Plugin ausgetauscht werden.

Ein Kandidat ist das neue Community-Plugin

https://github.com/capacitor-community/barcode-scanner

Wird aktiv weiter entwickelt und bietet denselben Funktionsumfang. API-Kompatibilität muss geprüft werden.

Siehe #19

**Comment by NVLGA** [comment]
@FSDRE Issue anlegen fürs Update von Capacitor, da in die dependencies reinschreiben, dass dieses issue dann beachtet werden muss
